objs_class_map:
  0: 'person'
  1: 'bicycle'
  2: 'car'
  3: 'motorcycle'
  4: 'bus'
  5: 'truck'

human_class: ['person', 'bicycle']

signs_class_map:
  0: 'traffic light'
  1: 'stop sign'

class_dimensions:
  car: { w: 1.8, h: 1.5, d: 4.5 }
  # van: { w: 2.0, h: 2.2, d: 5.0 }
  truck: { w: 2.5, h: 3.0, d: 8.0 }
  person: { w: 0.5, h: 1.7, d: 0.3 }
  bicycle: { w: 0.6, h: 1.7, d: 1.8 }
  motorcycle: { w: 2.5, h: 3.5, d: 15.0 }
  bus: { w: 0.5, h: 1.0, d: 0.5 }
  misc: { w: 1.0, h: 1.0, d: 1.0 }

sign_dimensions:
  stop sign: { w: 0.6, h: 2.0, d: 0.05, color: 0xFF0000 }
  traffic light: { w: 0.6, h: 2.0, d: 0.05, color: 0xFFAA00 }
  # speed_limit: { w: 0.6, h: 2.0, d: 0.05, color: 0xFFFFFF }
  # curveLeft: { w: 0.6, h: 2.0, d: 0.05, color: 0xFFFF00 }
  # curveRight: { w: 0.6, h: 2.0, d: 0.05, color: 0xFFFF00 }
  # pedestrianCrossing: { w: 0.6, h: 2.0, d: 0.05, color: 0x0000FF }
  unknown_sign: { w: 0.6, h: 2.0, d: 0.05, color: 0x888888 }

bev:
  # Trapezoid on the image corresponding to a rectangle on the ground in front of the camera
  # Top-left, Top-right, Bottom-right, Bottom-left
  # image_pts: [[220, 360], [420, 360], [540, 640], [100, 640]]
  image_pts: [[168, 547], [280, 553], [287, 575], [152,571]]
  # Corresponding real-world coordinates (x, y) in metres relative to the bike (origin)
  # Bike is at (0,0), +y is forward, +x is right
  # Top-left (-2m right, 10m forward), Top-right (+2m right, 10m forward)
  # Bottom-right (+2m right, 2m forward), Bottom-left (-2m right, 2m forward)
  # world_pts: [[-2.0, 10.0], [2.0, 10.0], [2.0, 2.0], [-2.0, 2.0]]
  world_pts: [[-0.5, 6.1], [0.42,6.1], [0.45, 5.1], [-0.53, 5.1]]  # Realistic camera intrinsic matrix for a 640x640 image
  # fx=600, fy=600, cx=320, cy=320
  camera_matrix: [
    [600.0, 0.0, 320.0], 
    [0.0, 600.0, 320.0], 
    [0.0, 0.0, 1.0]
  ]

default_class_dimension:
  w: 1.0
  h: 1.0
  d: 1.0

default_sign_dimension:
  w: 0.6
  h: 2.0
  d: 0.05
  color: 0x888888
